#AZIENDA
###
POST http://localhost:8080/api/v1/azienda/add/{{id}}

###
GET http://localhost:8080/api/v1/azienda/get/{{id}}

###
GET http://localhost:8080/api/v1/azienda/get/all

###
DELETE http://localhost:8080/api/v1/azienda/delete/{{id}}


#CAMPAGNA
###
POST http://localhost:8080/api/v1/campagna/add/{{id}}

###
GET http://localhost:8080/api/v1/campagna/get/{{id}}

###
GET http://localhost:8080/api/v1/campagna/get/all/{{id}}

###
DELETE http://localhost:8080/api/v1/campagna/delete/{{id}}


#CAMPO
###
POST http://localhost:8080/api/v1/campo/add/{{id}}

###
GET http://localhost:8080/api/v1/campo/get/{{id}}

###
GET http://localhost:8080/api/v1/campo/get/all/{{id}}

###
DELETE http://localhost:8080/api/v1/campo/delete/{{id}}


#COLTIVAZIONE
###
POST http://localhost:8080/api/v1/coltivazione/add/{{id}}

###
GET http://localhost:8080/api/v1/coltivazione/get/{{id}}

###
GET http://localhost:8080/api/v1/coltivazione/get/all/{{id}}

###
DELETE http://localhost:8080/api/v1/coltivazione/delete/{{id}}


#ATTUATORE
###
GET http://localhost:8080/api/v1/attuatore/get/{{id}}

###
GET http://localhost:8080/api/v1/attuatore/getCampo/{{id}}

###
POST http://localhost:8080/api/v1/attuatore/add/{{id}}

###
DELETE http://localhost:8080/api/v1/attuatore/delete/{{id}}


#ATTIVAZIONE
###
GET http://localhost:8080/api/v1/attivazione/get/{{id}}

###
GET http://localhost:8080/api/v1/attivazione/getAttuatore/{{id}}

###
POST http://localhost:8080/api/v1/attivazione/add/{{id}}

###
DELETE http://localhost:8080/api/v1/attivazione/delete/{{id}}


#SENSORE
###
GET http://localhost:8080/api/v1/sensore/get/{{id}}

###
GET http://localhost:8080/api/v1/sensore/getCampo/{{id}}

###
POST http://localhost:8080/api/v1/sensore/add/{{id}}

###
DELETE http://localhost:8080/api/v1/sensore/delete/{{id}}


#MISURA
###
POST http://localhost:8080/api/v1/misura/add/{{id}}

###
GET http://localhost:8080/api/v1/misura/get/{{id}}

###
GET http://localhost:8080/api/v1/misura/get/all/{{id}}

###
DELETE http://localhost:8080/api/v1/misura/delete/{{id}}


#BACINO
###
GET http://localhost:8080/api/v1/bacino/get/{{id}}

###
GET http://localhost:8080/api/v1/bacino/get/all

###
POST http://localhost:8080/api/v1/bacino/add/{{id}}

###
DELETE http://localhost:8080/api/v1/bacino/delete/{{id}}


#RISORSA
###
GET http://localhost:8080/api/v1/risorsa/getAzienda/{{id}}

###
GET http://localhost:8080/api/v1/risorsa/getAziendaStorico/{{id}}

###
POST http://localhost:8080/api/v1/risorsa/addAzienda/{{id}}

###
DELETE http://localhost:8080/api/v1/risorsa/deleteAzienda/{{id}}

###
GET http://localhost:8080/api/v1/risorsa/getBacino/{{id}}

###
GET http://localhost:8080/api/v1/risorsa/getBacinoStorico/{{id}}

###
POST http://localhost:8080/api/v1/risorsa/addBacino/{{id}}

###
DELETE http://localhost:8080/api/v1/risorsa/deleteBacino/{{id}}


#RICHIESTA
###
POST http://localhost:8080/api/v1/richiesta/add

###
GET http://localhost:8080/api/v1/richiesta/get/{{id}}

###
GET http://localhost:8080/api/v1/richiesta/get/allBacino/{{id}}

###
GET http://localhost:8080/api/v1/richiesta/get/allCampo/{{id}}

###
GET http://localhost:8080/api/v1/richiesta/get/allColtivazione/{{id}}


#APPROVAZIONE
###
GET http://localhost:8080/api/v1/approvazione/get/{{id}}

###
GET http://localhost:8080/api/v1/approvazione/getGestore/{{id}}

###
POST http://localhost:8080/api/v1/approvazione/add

###
DELETE http://localhost:8080/api/v1/approvazione/delete/{{id}}


#USER
###
GET http://localhost:8080/api/v1/users/admin

###
GET http://localhost:8080/api/v1/users/get

###
GET http://localhost:8080/api/v1/users/get/ga

###
GET http://localhost:8080/api/v1/users/get/gi

###
GET http://localhost:8080/api/v1/users/getAll

###
POST http://localhost:8080/api/v1/users/add

###
DELETE http://localhost:8080/api/v1/users/delete

#RACCOLTO
###
GET http://localhost:8080/api/v1/raccolto/raccolto/get/all

###
POST http://localhost:8080/api/v1/raccolto/raccolto/add/{{nome}}

###
DELETE http://localhost:8080/api/v1/raccolto/raccolto/delete/{{nome}}

###
GET http://localhost:8080/api/v1/raccolto/esigenza/get/all

###
POST http://localhost:8080/api/v1/raccolto/esigenza/add/{{nome}}

###
DELETE http://localhost:8080/api/v1/raccolto/esigenza/delete/{{nome}}

###
GET http://localhost:8080/api/v1/raccolto/irrigazione/get/all

###
POST http://localhost:8080/api/v1/raccolto/irrigazione/add/{{nome}}

###
DELETE http://localhost:8080/api/v1/raccolto/irrigazione/delete/{{nome}}