/* 
 * 
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using NUnit.Framework;

using IO.Swagger.Client;
using IO.Swagger.Api;

namespace IO.Swagger.Test
{
    /// <summary>
    ///  Class for testing ControllerRisorsaIdricaApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    [TestFixture]
    public class ControllerRisorsaIdricaApiTests
    {
        private ControllerRisorsaIdricaApi instance;

        /// <summary>
        /// Setup before each unit test
        /// </summary>
        [SetUp]
        public void Init()
        {
            instance = new ControllerRisorsaIdricaApi();
        }

        /// <summary>
        /// Clean up after each unit test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of ControllerRisorsaIdricaApi
        /// </summary>
        [Test]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsInstanceOfType' ControllerRisorsaIdricaApi
            //Assert.IsInstanceOfType(typeof(ControllerRisorsaIdricaApi), instance, "instance is a ControllerRisorsaIdricaApi");
        }

        /// <summary>
        /// Test AddRisorsaAzienda
        /// </summary>
        [Test]
        public void AddRisorsaAziendaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //var response = instance.AddRisorsaAzienda(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test AddRisorsaBacino
        /// </summary>
        [Test]
        public void AddRisorsaBacinoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string body = null;
            //var response = instance.AddRisorsaBacino(body);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test DeleteRisorsaAzienda
        /// </summary>
        [Test]
        public void DeleteRisorsaAziendaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.DeleteRisorsaAzienda(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test DeleteRisorsaBacino
        /// </summary>
        [Test]
        public void DeleteRisorsaBacinoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.DeleteRisorsaBacino(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetRisorsaAziendaId
        /// </summary>
        [Test]
        public void GetRisorsaAziendaIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetRisorsaAziendaId(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetRisorsaBacinoId
        /// </summary>
        [Test]
        public void GetRisorsaBacinoIdTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetRisorsaBacinoId(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetStoricoRisorseAzienda
        /// </summary>
        [Test]
        public void GetStoricoRisorseAziendaTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetStoricoRisorseAzienda(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
        /// <summary>
        /// Test GetStoricoRisorseBacino
        /// </summary>
        [Test]
        public void GetStoricoRisorseBacinoTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? id = null;
            //var response = instance.GetStoricoRisorseBacino(id);
            //Assert.IsInstanceOf<string> (response, "response is string");
        }
    }

}
